Date:
  start: "2007-12-25"
  end: "2023-06-01"
RANDOM_SEED: 0
# UNIVERSE_SIZE: 16
# NUM_COMBINATION: 1000
NUM_HOLDING_ETF: 4
NUM_REVENUE_GROWTH_RANK: 10
HOLDING_PERIOD_LENGTH: 1
HOLDING_PERIOD_TYPES: ["months", "quarters", "years"]

PRIMARY_FILTER: "US_etf_23-01-02_thematic_score$daily$3_C4zLKF1-Z"
SECONADRY_FILTER: "US_etf_23-01-02_sharpe_ratio_3m$daily$4_wkE9ZvEWH"

Themes:
  - NASDAQ:AIA: 1263 
  - NASDAQ:IBB: 4545 
  - NASDAQ:IEUS: 4602 
  - NASDAQ:IGF: 4626  
  - NYSE:IVV: 2572063 
  - NYSE:IXN: 2572064  
  - NYSE:IXJ: 2572065 
  - NYSE:BKF: 2572181  
  - NYSE:DGS: 2572350 
  - NYSE:EPP: 2572468  
  - NYSE:EWH: 2572510 
  - NYSE:EWY: 2572537  
  - NYSE:FDN: 2572561 
  - NYSE:GXC: 2572759  
  - NYSE:IHI: 2572878 
  - NYSE:ILF: 2572891  
  - NYSE:IXG: 2572959 
  - NYSE:JXI: 2573028  
  - NYSE:PBE: 2573222 
  - NYSE:PEJ: 2573232  
  - NYSE:RXI: 2573420 
  - NYSE:SCJ: 2573464  
  - NYSE:VB: 2573756  
  - NYSE:VDE: 2573762 
  - NYSE:VFH: 2573768  
  - NYSE:VGK: 2573769 
  - NYSE:VGT: 2573770  
  - NYSE:VHT: 2573772 
  - NYSE:VO: 2573791 
  - NYSE:XBI: 2573845  
  - NYSE:XLK: 2573862 
  - NYSE:XLV: 2573867  
  - NYSE:XME: 2573870