Date:
  start: "2017-12-25"
  end: "2023-08-15"
RANDOM_SEED: 0
NUM_HOLDING_ETF: 4
NUM_REVENUE_GROWTH_RANK: 10
HOLDING_PERIOD_LENGTH: 1
HOLDING_PERIOD_TYPES: ["months", "quarters", "years"]

Themes:
  - NYSE:ONLN: 2572066
  - NASDAQ:XT: 8893
  - NYSE:IXJ: 2572065
  - NYSE:IRBO: 2572067
  - NASDAQ:WCLD: 497280
  - NASDAQ:HERO: 851607
  - NASDAQ:FINX: 3695
  - NYSE:CQQQ: 2572286
  - NYSE:MJ: 2573125
  - NYSE:AWAY: 2577965
  - NYSE:IDNA: 2572856
  - NASDAQ:ICLN: 4572
  - NASDAQ:SNSR: 7634 
  - NYSE:KGRN: 2573042
  - NYSE:KURE: 2573062
  - NYSE:METV: 2583162
  - NASDAQ:CIBR: 2419
  - NYSE:LIT: 2573085
  - NASDAQ:SMH: 1232815
