apiVersion: batch/v1
kind: Job
metadata:
  name: marketvaluation
spec:
  ttlSecondsAfterFinished: 60
  completions: 1
  template:
    spec:
      containers:
        - name: marketvaluation
          image: asia.gcr.io/jitta-dev/marketvaluation:latest
          command: ["/bin/sh", "-c"]
          args:
            [
              "pipenv run python loop_peband_monthly.py",
            ]
      restartPolicy: OnFailure
